version: '3.7'

services:
  mariadb:
    image: mariadb:${MARIADB_VERSION}
    container_name: mariadb-${ID}
    environment:
      - MYSQL_ROOT_PASSWORD=${MARIADB_ROOT_PW}
      - MYSQL_DATABASE=${MARIADB_SCHEMA}
      - MYSQL_USER=${MARIADB_USER}
      - MYSQL_PASSWORD=${MARIADB_PW}
    volumes:
      - ${MARIADB_VOLUME}:/var/lib/mysql
    ports:
      - '${MARIADB_EXT_PORT}:3306'
    networks:
      - devh-network
      
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ES_VERSION}
    container_name: elasticsearch-${ID}
    environment:
      - cluster.initial_master_nodes=${ES_MASTER_NODE}
      - cluster.name=${ES_CLUSTER_NAME}
      - node.name=${ES_NODE_NAME}
      - network.host=${ES_NETWORK_HOST}
      - bootstrap.memory_lock=${ES_BOOTSTRAP_MEMORY_LOCK}
      - "ES_JAVA_OPTS=-Xms${ES_MEMORY}m -Xmx${ES_MEMORY}m"
    volumes:
      - ${ES_VOLUME}:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - '${ES_EXT_PORT}:9200'
    networks:
      - devh-network
      
networks:
  devh-network:
    external: true

